# Data_receivied =  {'active': True, 'comments': '', 'correlation_id': '5768925723754496', 'created_at': '2020-10-28T13:45:59.315', 'created_by': 'davidcorreia', 'expected_service': 'navigo-simba-po-default', 'expected_service_changed_at': None, 'expected_service_changed_by': None, 'form_id': 91, 'form_team': {'description': None, 'form_id': 91, 'form_type': 'procurement_support', 'form_uuid': '7c3b3b06-d787-41b8-b2ef-25fe1baf56a4', 'id': 79, 'team': {'cost_center': None, 'cost_center_id': 65, 'description': None, 'id': 1, 'name': '362: Strategy & Operations', 'parent_id': None, 'prefix': None, 'sandbox_id_counter': None, 'type': 'team'}, 'team_id': 1}, 'form_team_id': 79, 'form_type': 'procurement_support', 'id': 76, 'navigo_id': None, 'navigo_risk': None, 'operation': 'update', 'owner': 'davidcorreia', 'permissions': {'edit': False}, 'placeholder': {'id': 76, 'sandbox_id': 'SO229', 'status_display': '-'}, 'placeholder_id': 76, 'po_number': None, 'processed': False, 'sandbox_id': '', 'sandbox_sections': [{'option': {'id': 2, 'name': 'NAVIGO, SIMBA, PO [Default]', 'question_id': 'expected_service', 'section_id': None, 'value': 'navigo-simba-po-default'}, 'path': '/expected_service', 'question_id': 'expected_service', 'value': 'navigo-simba-po-default'}], 'sections': [{'option': {'id': 3105, 'name': 'No', 'question_id': 1602, 'section_id': None, 'value': 'Value 1'}, 'path': '/1602', 'question_id': 1602, 'value': 'Value 1'}, {'option': None, 'path': '/770', 'question_id': 770, 'value': '15511'}, {'option': {'id': 1536, 'name': 'USD', 'question_id': 771, 'section_id': None, 'value': 'Value 2'}, 'path': '/771', 'question_id': 771, 'value': 'Value 2'}, {'option': None, 'path': '/902', 'question_id': 902, 'value': 'test updated '}, {'option': None, 'path': '/772', 'question_id': 772, 'value': 'test updated'}, {'option': None, 'path': '/773', 'question_id': 773, 'value': 'test updated'}, {'option': None, 'path': '/774', 'question_id': 774, 'value': 'test updated'}, {'option': None, 'path': '/775', 'question_id': 775, 'value': '2020-10-23'}, {'option': None, 'path': '/776', 'question_id': 776, 'value': '2020-10-30'}, {'option': {'id': 1539, 'name': 'No', 'question_id': 777, 'section_id': None, 'value': 'Value 2'}, 'path': '/777', 'question_id': 777, 'value': 'Value 2'}, {'option': {'id': 1809, 'name': 'No', 'question_id': 889, 'section_id': None, 'value': 'Value 2'}, 'path': '/889', 'question_id': 889, 'value': 'Value 2'}, {'option': {'id': 1811, 'name': 'No', 'question_id': 890, 'section_id': None, 'value': 'Value 2'}, 'path': '/890', 'question_id': 890, 'value': 'Value 2'}, {'option': {'id': 1813, 'name': 'No', 'question_id': 891, 'section_id': None, 'value': 'Value 2'}, 'path': '/891', 'question_id': 891, 'value': 'Value 2'}, {'option': {'id': 1815, 'name': 'No', 'question_id': 892, 'section_id': None, 'value': 'Value 2'}, 'path': '/892', 'question_id': 892, 'value': 'Value 2'}, {'option': {'id': 1937, 'name': 'Option 2', 'question_id': 778, 'section_id': None, 'value': 'Value 2'}, 'path': '/778', 'question_id': 778, 'value': 'Value 2'}, {'option': {'id': 1817, 'name': 'WIN THE C-SUITE', 'question_id': 893, 'section_id': None, 'value': 'Value 2'}, 'path': '/893', 'question_id': 893, 'value': 'Value 2'}, {'option': {'id': 1823, 'name': 'GCP', 'question_id': 894, 'section_id': None, 'value': 'Value 2'}, 'path': '/894', 'question_id': 894, 'value': 'Value 2'}, {'option': None, 'path': '/895', 'question_id': 895, 'value': 'test updated'}, {'option': None, 'path': '/896', 'question_id': 896, 'value': 'test updated'}, {'option': None, 'path': '/779', 'question_id': 779, 'value': 'test updated'}, {'option': None, 'path': '/780', 'question_id': 780, 'value': 'test updated'}, {'option': None, 'path': '/781', 'question_id': 781, 'value': 'test updated'}, {'option': None, 'path': '/782', 'question_id': 782, 'value': 'test updated'}, {'option': None, 'path': '/903', 'question_id': 903, 'value': 'test updated'}, {'option': {'id': 1834, 'name': 'Q1, Q2, Q3, Q4', 'question_id': 904, 'section_id': None, 'value': 'Value 4'}, 'path': '/904', 'question_id': 904, 'value': 'Value 4'}], 'simba_id': None, 'status_display': '_', 'team_id': 1, 'updated_at': '2020-10-28T14:31:06.199', 'updated_by': 'davidcorreia'}
#
#
#
# data_woven = {'active': True,
#  'buganizer_id': 171869909,
#  'comments': '',
#  'correlation_id': '5637558813851648',
#  'created_at': '2020-10-28T13:28:25.458',
#  'created_by': 'davidcorreia',
#  'expected_service': 'only-navigo-simba',
#  'expected_service_changed_at': '2020-10-28T13:55:35.216',
#  'expected_service_changed_by': 'davidcorreia',
#  'form_team': {'description': None,
#   'form_id': 91,
#   'form_type': 'procurement_support',
#   'form_uuid': '7c3b3b06-d787-41b8-b2ef-25fe1baf56a4',
#   'id': 79,
#   'team': {'cost_center': None,
#    'cost_center_id': 65,
#    'description': None,
#    'id': 1,
#    'name': '362: Strategy & Operations',
#    'parent_id': None,
#    'prefix': None,
#    'sandbox_id_counter': None,
#    'type': 'team'},
#   'team_id': 1},
#  'form_team_id': 79,
#  'form_type': 'procurement_support',
#  'id': 77,
#  'navigo_id': None,
#  'navigo_risk': None,
#  'owner': 'davidcorreia',
#  'permissions': {'edit': False},
#  'placeholder': {'cost_center': '362: Marketing Analytics & Ops - Database',
#   'id': 77,
#   'sandbox_id': 'SO230',
#   'status': 'requested',
#   'status_display': 'Requested'},
#  'placeholder_id': 77,
#  'po_number': None,
#  'processed': True,
#  'sandbox_id': '',
#  'simba_id': None,
#  'status_display': '_',
#  'updated_at': '2020-10-28T13:55:34.900',
#  'updated_by': 'davidcorreia'}
#
# data_woven_edit =  {'active': True,
#  'comments': '',
#  'correlation_id': '5768925723754496',
#  'created_at': '2020-10-28T13:45:59.315',
#  'created_by': 'davidcorreia',
#  'expected_service': 'navigo-simba-po-default',
#  'expected_service_changed_at': None,
#  'expected_service_changed_by': None,
#  'form_id': 91,
#  'form_team': {'description': None,
#   'form_id': 91,
#   'form_type': 'procurement_support',
#   'form_uuid': '7c3b3b06-d787-41b8-b2ef-25fe1baf56a4',
#   'id': 79,
#   'team': {'cost_center': None,
#    'cost_center_id': 65,
#    'description': None,
#    'id': 1,
#    'name': '362: Strategy & Operations',
#    'parent_id': None,
#    'prefix': None,
#    'sandbox_id_counter': None,
#    'type': 'team'},
#   'team_id': 1},
#  'form_team_id': 79,
#  'form_type': 'procurement_support',
#  'id': 76,
#  'navigo_id': None,
#  'navigo_risk': None,
#  'operation': 'update',
#  'owner': 'davidcorreia',
#  'permissions': {'edit': False},
#  'placeholder': {'id': 76, 'sandbox_id': 'SO229', 'status_display': '-'},
#  'placeholder_id': 76,
#  'po_number': None,
#  'processed': False,
#  'sandbox_id': '',
#  'sandbox_sections': [{'option': {'id': 2,
#     'name': 'NAVIGO, SIMBA, PO [Default]',
#     'question_id': 'expected_service',
#     'section_id': None,
#     'value': 'navigo-simba-po-default'},
#    'path': '/expected_service',
#    'question_id': 'expected_service',
#    'value': 'navigo-simba-po-default'}],
#  'sections': [{'option': {'id': 3105,
#     'name': 'No',
#     'question_id': 1602,
#     'section_id': None,
#     'value': 'Value 1'},
#    'path': '/1602',
#    'question_id': 1602,
#    'value': 'Value 1'},
#   {'option': None, 'path': '/770', 'question_id': 770, 'value': '15511'},
#   {'option': {'id': 1536,
#     'name': 'USD',
#     'question_id': 771,
#     'section_id': None,
#     'value': 'Value 2'},
#    'path': '/771',
#    'question_id': 771,
#    'value': 'Value 2'},
#   {'option': None,
#    'path': '/902',
#    'question_id': 902,
#    'value': 'test updated '},
#   {'option': None,
#    'path': '/772',
#    'question_id': 772,
#    'value': 'test updated'},
#   {'option': None,
#    'path': '/773',
#    'question_id': 773,
#    'value': 'test updated'},
#   {'option': None,
#    'path': '/774',
#    'question_id': 774,
#    'value': 'test updated'},
#   {'option': None, 'path': '/775', 'question_id': 775, 'value': '2020-10-23'},
#   {'option': None, 'path': '/776', 'question_id': 776, 'value': '2020-10-30'},
#   {'option': {'id': 1539,
#     'name': 'No',
#     'question_id': 777,
#     'section_id': None,
#     'value': 'Value 2'},
#    'path': '/777',
#    'question_id': 777,
#    'value': 'Value 2'},
#   {'option': {'id': 1809,
#     'name': 'No',
#     'question_id': 889,
#     'section_id': None,
#     'value': 'Value 2'},
#    'path': '/889',
#    'question_id': 889,
#    'value': 'Value 2'},
#   {'option': {'id': 1811,
#     'name': 'No',
#     'question_id': 890,
#     'section_id': None,
#     'value': 'Value 2'},
#    'path': '/890',
#    'question_id': 890,
#    'value': 'Value 2'},
#   {'option': {'id': 1813,
#     'name': 'No',
#     'question_id': 891,
#     'section_id': None,
#     'value': 'Value 2'},
#    'path': '/891',
#    'question_id': 891,
#    'value': 'Value 2'},
#   {'option': {'id': 1815,
#     'name': 'No',
#     'question_id': 892,
#     'section_id': None,
#     'value': 'Value 2'},
#    'path': '/892',
#    'question_id': 892,
#    'value': 'Value 2'},
#   {'option': {'id': 1937,
#     'name': 'Option 2',
#     'question_id': 778,
#     'section_id': None,
#     'value': 'Value 2'},
#    'path': '/778',
#    'question_id': 778,
#    'value': 'Value 2'},
#   {'option': {'id': 1817,
#     'name': 'WIN THE C-SUITE',
#     'question_id': 893,
#     'section_id': None,
#     'value': 'Value 2'},
#    'path': '/893',
#    'question_id': 893,
#    'value': 'Value 2'},
#   {'option': {'id': 1823,
#     'name': 'GCP',
#     'question_id': 894,
#     'section_id': None,
#     'value': 'Value 2'},
#    'path': '/894',
#    'question_id': 894,
#    'value': 'Value 2'},
#   {'option': None,
#    'path': '/895',
#    'question_id': 895,
#    'value': 'test updated'},
#   {'option': None,
#    'path': '/896',
#    'question_id': 896,
#    'value': 'test updated'},
#   {'option': None,
#    'path': '/779',
#    'question_id': 779,
#    'value': 'test updated'},
#   {'option': None,
#    'path': '/780',
#    'question_id': 780,
#    'value': 'test updated'},
#   {'option': None,
#    'path': '/781',
#    'question_id': 781,
#    'value': 'test updated'},
#   {'option': None,
#    'path': '/782',
#    'question_id': 782,
#    'value': 'test updated'},
#   {'option': None,
#    'path': '/903',
#    'question_id': 903,
#    'value': 'test updated'},
#   {'option': {'id': 1834,
#     'name': 'Q1, Q2, Q3, Q4',
#     'question_id': 904,
#     'section_id': None,
#     'value': 'Value 4'},
#    'path': '/904',
#    'question_id': 904,
#    'value': 'Value 4'}],
#  'simba_id': None,
#  'status_display': '_',
#  'team_id': 1,
#  'updated_at': '2020-10-28T14:31:06.199',
#  'updated_by': 'davidcorreia'}
#
#
# print(data_woven.get('form_team')['form_id'])


def execute(string):
    pass


test = {'active': True, 'buganizer_id': 171869909, 'comments': '', 'correlation_id': '5637558813851648', 'created_at': '2020-10-28T13:28:25.458', 'created_by': 'davidcorreia', 'expected_service': 'only-navigo-simba', 'expected_service_changed_at': '2020-10-28T13:55:35.216', 'expected_service_changed_by': 'davidcorreia', 'form_team': {'description': None,  'form_id': 91,  'form_type': 'procurement_support',  'form_uuid': '7c3b3b06-d787-41b8-b2ef-25fe1baf56a4',  'id': 79,  'team': {'cost_center': None,   'cost_center_id': 65,   'description': None,   'id': 1,   'name': '362: Strategy & Operations',   'parent_id': None,   'prefix': None,   'sandbox_id_counter': None,   'type': 'team'},  'team_id': 1}, 'form_team_id': 79, 'form_type': 'procurement_support', 'id': 77, 'navigo_id': None, 'navigo_risk': None, 'operation': 'update', 'owner': 'davidcorreia', 'permissions': {'edit': False}, 'placeholder': {'cost_center': '362: Marketing Analytics & Ops - Database',  'id': 77,  'sandbox_id': 'SO230',  'status': 'requested',  'status_display': 'Requested'}, 'placeholder_id': 77, 'po_number': None, 'processed': True, 'sandbox_id': '', 'simba_id': None, 'status_display': '_', 'updated_at': '2020-10-28T13:55:34.900', 'updated_by': 'davidcorreia'}                        [{'option': {'id': 3308,   'name': 'No',   'question_id': 1749,   'section_id': None,   'value': 'Value 2'},  'path': '/1749',  'question_id': 1749,  'value': 'Value 2'}, {'option': {'id': 1941,   'name': 'LATAM',   'question_id': 999,   'section_id': None,   'value': 'Value 4'},  'path': '/999',  'question_id': 999,  'value': 'Value 4'}, {'option': None,  'path': '/1002',  'question_id': 1002,  'value': 'Activity Description test'}, {'option': {'id': 1951,   'name': 'Systems',   'question_id': 1003,   'section_id': None,   'value': 'Value 2'},  'path': '/1003',  'question_id': 1003,  'value': 'Value 2'}, {'option': {'id': 3361,   'name': 'Prio 1',   'question_id': 1776,   'section_id': None,   'value': 'Value 1'},  'path': '/1776',  'question_id': 1776,  'value': 'Value 1'}]
execute({'active': True, 'comments': '', 'correlation_id': '5768925723754496', 'created_at': '2020-10-28T13:45:59.315', 'created_by': 'davidcorreia', 'expected_service': 'navigo-simba-po-default', 'expected_service_changed_at': None, 'expected_service_changed_by': None, 'form_id': 91, 'form_team': {'description': None, 'form_id': 91, 'form_type': 'procurement_support', 'form_uuid': '7c3b3b06-d787-41b8-b2ef-25fe1baf56a4', 'id': 79, 'team': {'cost_center': None, 'cost_center_id': 65, 'description': None, 'id': 1, 'name': '362: Strategy & Operations', 'parent_id': None, 'prefix': None, 'sandbox_id_counter': None, 'type': 'team'}, 'team_id': 1}, 'form_team_id': 79, 'form_type': 'procurement_support', 'id': 76, 'navigo_id': None, 'navigo_risk': None, 'operation': 'update', 'owner': 'davidcorreia', 'permissions': {'edit': False}, 'placeholder': {'id': 76, 'sandbox_id': 'SO229', 'status_display': '-'}, 'placeholder_id': 76, 'po_number': None, 'processed': False, 'sandbox_id': '', 'sandbox_sections': [{'option': {'id': 2, 'name': 'NAVIGO, SIMBA, PO [Default]', 'question_id': 'expected_service', 'section_id': None, 'value': 'navigo-simba-po-default'}, 'path': '/expected_service', 'question_id': 'expected_service', 'value': 'navigo-simba-po-default'}], 'sections': [{'option': {'id': 3105, 'name': 'No', 'question_id': 1602, 'section_id': None, 'value': 'Value 1'}, 'path': '/1602', 'question_id': 1602, 'value': 'Value 1'}, {'option': None, 'path': '/770', 'question_id': 770, 'value': '15511'}, {'option': {'id': 1536, 'name': 'USD', 'question_id': 771, 'section_id': None, 'value': 'Value 2'}, 'path': '/771', 'question_id': 771, 'value': 'Value 2'}, {'option': None, 'path': '/902', 'question_id': 902, 'value': 'test updated '}, {'option': None, 'path': '/772', 'question_id': 772, 'value': 'test updated'}, {'option': None, 'path': '/773', 'question_id': 773, 'value': 'test updated'}, {'option': None, 'path': '/774', 'question_id': 774, 'value': 'test updated'}, {'option': None, 'path': '/775', 'question_id': 775, 'value': '2020-10-23'}, {'option': None, 'path': '/776', 'question_id': 776, 'value': '2020-10-30'}, {'option': {'id': 1539, 'name': 'No', 'question_id': 777, 'section_id': None, 'value': 'Value 2'}, 'path': '/777', 'question_id': 777, 'value': 'Value 2'}, {'option': {'id': 1809, 'name': 'No', 'question_id': 889, 'section_id': None, 'value': 'Value 2'}, 'path': '/889', 'question_id': 889, 'value': 'Value 2'}, {'option': {'id': 1811, 'name': 'No', 'question_id': 890, 'section_id': None, 'value': 'Value 2'}, 'path': '/890', 'question_id': 890, 'value': 'Value 2'}, {'option': {'id': 1813, 'name': 'No', 'question_id': 891, 'section_id': None, 'value': 'Value 2'}, 'path': '/891', 'question_id': 891, 'value': 'Value 2'}, {'option': {'id': 1815, 'name': 'No', 'question_id': 892, 'section_id': None, 'value': 'Value 2'}, 'path': '/892', 'question_id': 892, 'value': 'Value 2'}, {'option': {'id': 1937, 'name': 'Option 2', 'question_id': 778, 'section_id': None, 'value': 'Value 2'}, 'path': '/778', 'question_id': 778, 'value': 'Value 2'}, {'option': {'id': 1817, 'name': 'WIN THE C-SUITE', 'question_id': 893, 'section_id': None, 'value': 'Value 2'}, 'path': '/893', 'question_id': 893, 'value': 'Value 2'}, {'option': {'id': 1823, 'name': 'GCP', 'question_id': 894, 'section_id': None, 'value': 'Value 2'}, 'path': '/894', 'question_id': 894, 'value': 'Value 2'}, {'option': None, 'path': '/895', 'question_id': 895, 'value': 'test updated'}, {'option': None, 'path': '/896', 'question_id': 896, 'value': 'test updated'}, {'option': None, 'path': '/779', 'question_id': 779, 'value': 'test updated'}, {'option': None, 'path': '/780', 'question_id': 780, 'value': 'test updated'}, {'option': None, 'path': '/781', 'question_id': 781, 'value': 'test updated'}, {'option': None, 'path': '/782', 'question_id': 782, 'value': 'test updated'}, {'option': None, 'path': '/903', 'question_id': 903, 'value': 'test updated'}, {'option': {'id': 1834, 'name': 'Q1, Q2, Q3, Q4', 'question_id': 904, 'section_id': None, 'value': 'Value 4'}, 'path': '/904', 'question_id': 904, 'value': 'Value 4'}], 'simba_id': None, 'status_display': '_', 'team_id': 1, 'updated_at': '2020-10-28T14:31:06.199', 'updated_by': 'davidcorreia'})
execute({'active': True, 'comments': '', 'correlation_id': '5768925723754496', 'created_at': '2020-10-28T13:45:59.315', 'created_by': 'davidcorreia', 'expected_service': 'navigo-simba-po-default', 'expected_service_changed_at': None, 'expected_service_changed_by': None, 'form_id': 91, 'form_team': {'description': None, 'form_id': 91, 'form_type': 'procurement_support', 'form_uuid': '7c3b3b06-d787-41b8-b2ef-25fe1baf56a4', 'id': 79, 'team': {'cost_center': None, 'cost_center_id': 65, 'description': None, 'id': 1, 'name': '362: Strategy & Operations', 'parent_id': None, 'prefix': None, 'sandbox_id_counter': None, 'type': 'team'}, 'team_id': 1}, 'form_team_id': 79, 'form_type': 'procurement_support', 'id': 76, 'navigo_id': None, 'navigo_risk': None, 'operation': 'update', 'owner': 'davidcorreia', 'permissions': {'edit': False}, 'placeholder': {'id': 76, 'sandbox_id': 'SO229', 'status_display': '-'}, 'placeholder_id': 76, 'po_number': None, 'processed': False, 'sandbox_id': '', 'sandbox_sections': [{'option': {'id': 2, 'name': 'NAVIGO, SIMBA, PO [Default]', 'question_id': 'expected_service', 'section_id': None, 'value': 'navigo-simba-po-default'}, 'path': '/expected_service', 'question_id': 'expected_service', 'value': 'navigo-simba-po-default'}], 'sections': [{'option': {'id': 3105, 'name': 'No', 'question_id': 1602, 'section_id': None, 'value': 'Value 1'}, 'path': '/1602', 'question_id': 1602, 'value': 'Value 1'}, {'option': None, 'path': '/770', 'question_id': 770, 'value': '15511'}, {'option': {'id': 1536, 'name': 'USD', 'question_id': 771, 'section_id': None, 'value': 'Value 2'}, 'path': '/771', 'question_id': 771, 'value': 'Value 2'}, {'option': None, 'path': '/902', 'question_id': 902, 'value': 'test updated '}, {'option': None, 'path': '/772', 'question_id': 772, 'value': 'test updated'}, {'option': None, 'path': '/773', 'question_id': 773, 'value': 'test updated'}, {'option': None, 'path': '/774', 'question_id': 774, 'value': 'test updated'}, {'option': None, 'path': '/775', 'question_id': 775, 'value': '2020-10-23'}, {'option': None, 'path': '/776', 'question_id': 776, 'value': '2020-10-30'}, {'option': {'id': 1539, 'name': 'No', 'question_id': 777, 'section_id': None, 'value': 'Value 2'}, 'path': '/777', 'question_id': 777, 'value': 'Value 2'}, {'option': {'id': 1809, 'name': 'No', 'question_id': 889, 'section_id': None, 'value': 'Value 2'}, 'path': '/889', 'question_id': 889, 'value': 'Value 2'}, {'option': {'id': 1811, 'name': 'No', 'question_id': 890, 'section_id': None, 'value': 'Value 2'}, 'path': '/890', 'question_id': 890, 'value': 'Value 2'}, {'option': {'id': 1813, 'name': 'No', 'question_id': 891, 'section_id': None, 'value': 'Value 2'}, 'path': '/891', 'question_id': 891, 'value': 'Value 2'}, {'option': {'id': 1815, 'name': 'No', 'question_id': 892, 'section_id': None, 'value': 'Value 2'}, 'path': '/892', 'question_id': 892, 'value': 'Value 2'}, {'option': {'id': 1937, 'name': 'Option 2', 'question_id': 778, 'section_id': None, 'value': 'Value 2'}, 'path': '/778', 'question_id': 778, 'value': 'Value 2'}, {'option': {'id': 1817, 'name': 'WIN THE C-SUITE', 'question_id': 893, 'section_id': None, 'value': 'Value 2'}, 'path': '/893', 'question_id': 893, 'value': 'Value 2'}, {'option': {'id': 1823, 'name': 'GCP', 'question_id': 894, 'section_id': None, 'value': 'Value 2'}, 'path': '/894', 'question_id': 894, 'value': 'Value 2'}, {'option': None, 'path': '/895', 'question_id': 895, 'value': 'test updated'}, {'option': None, 'path': '/896', 'question_id': 896, 'value': 'test updated'}, {'option': None, 'path': '/779', 'question_id': 779, 'value': 'test updated'}, {'option': None, 'path': '/780', 'question_id': 780, 'value': 'test updated'}, {'option': None, 'path': '/781', 'question_id': 781, 'value': 'test updated'}, {'option': None, 'path': '/782', 'question_id': 782, 'value': 'test updated'}, {'option': None, 'path': '/903', 'question_id': 903, 'value': 'test updated'}, {'option': {'id': 1834, 'name': 'Q1, Q2, Q3, Q4', 'question_id': 904, 'section_id': None, 'value': 'Value 4'}, 'path': '/904', 'question_id': 904, 'value': 'Value 4'}], 'simba_id': None, 'status_display': '_', 'team_id': 1, 'updated_at': '2020-10-28T14:31:06.199', 'updated_by': 'davidcorreia'})

test = {"test": "test2"}
print(test.get('test'))