data = {'active': True,
 'amount': 250000.0,
 'budget_plan': [{'amount': 250000.0,
   'discriminator': 'placeholder',
   'fiscal_year': 2021,
   'id': None,
   'parent_id': 24,
   'quarter': 'Q2'}],
 'correlation_id': 5675337346187264,
 'cost_center': '362: Marketing Analytics & Ops - Optimization',
 'cost_center_id': 5,
 'created_at': '2020-10-23T12:43:51.669',
 'created_by': 'davidcorreia',
 'form_id': 123,
 'form_team': {'description': None,
  'form_id': 123,
  'form_type': 'placeholder',
  'form_uuid': '2d6e1512-1ad6-4ac8-aa5e-316a85f6e157',
  'id': 83,
  'team': {'cost_center': None,
   'cost_center_id': 65,
   'description': None,
   'id': 1,
   'name': '362: Strategy & Operations',
   'parent_id': None,
   'prefix': None,
   'sandbox_id_counter': None,
   'type': 'team'},
  'team_id': 1},
 'form_team_id': 83,
 'form_type': 'placeholder',
 'has_procurement_support': False,
 'hidden': False,
 'id': 24,
 'non_program': 'infrastructure',
 'operation': 'update',
 'owner': 'davidcorreia',
 'permissions': {'edit': False,
  'edit_business_services_fields': False,
  'edit_procurement_support': False,
  'request_procurement_support': False},
 'processed': False,
 'procurement_support': None,
 'program_instance': None,
 'program_instance_id': None,
 'program_non_program_name': None,
 'quarters': '21/Q2',
 'sandbox_id': 'SO177',
 'sandbox_sections': [{'option': {'id': 5,
    'name': '362: Marketing Analytics & Ops - Optimization',
    'question_id': 'cost_center',
    'section_id': None,
    'value': '5'},
   'path': '/cost_center',
   'question_id': 'cost_center',
   'value': '5'},
  {'option': {'id': 1,
    'name': 'Infrastructure',
    'question_id': 'non_program',
    'section_id': None,
    'value': 'infrastructure'},
   'path': '/non_program',
   'question_id': 'non_program',
   'value': 'infrastructure'},
  {'option': None,
   'path': '/budget_plan',
   'question_id': 'budget_plan',
   'value': '[{"fiscal_year":2021,"quarter":"Q2","amount":250000}]'},
  {'option': {'id': 1,
    'name': 'TVC: Contractor',
    'question_id': 'spend_type',
    'section_id': None,
    'value': 'tvc-contractor'},
   'path': '/spend_type',
   'question_id': 'spend_type',
   'value': 'tvc-contractor'}],
 'sections': [{'option': {'id': 3308,
    'name': 'No',
    'question_id': 1749,
    'section_id': None,
    'value': 'Value 2'},
   'path': '/1749',
   'question_id': 1749,
   'value': 'Value 2'},
  {'option': {'id': 1940,
    'name': 'NORTHAM',
    'question_id': 999,
    'section_id': None,
    'value': 'Value 3'},
   'path': '/999',
   'question_id': 999,
   'value': 'Value 3'},
  {'option': None, 'path': '/1002', 'question_id': 1002, 'value': None},
  {'option': None, 'path': '/1003', 'question_id': 1003, 'value': None},
  {'option': {'id': 3361,
    'name': 'Prio 1',
    'question_id': 1776,
    'section_id': None,
    'value': 'Value 1'},
   'path': '/1776',
   'question_id': 1776,
   'value': 'Value 1'}],
 'spend_type': 'tvc-contractor',
 'status': 'process-started',
 'status_display': 'Process Started',
 'team_id': 1,
 'updated_at': '2020-10-23T12:49:11.580',
 'updated_by': 'davidcorreia'}

data['cost_center'] = "trocar"
print(data['cost_center'])