'''
FAÇA UM PROGRAMA QUE LEIA NOME E MÉDIA DE UM ALUNO, GUARDANDO TAMB[EM A SITUA;ÁO EM UM
DICIONARIO. NO FINAL MOSTRE O CONTEUDO DA ESTRUTURA NA TELA

PRINT
NOME: XXXX = INPUT
MEDIA DE XXXX = INPUT

PRINT RESULT
NOME E IGUA A XXXX
MEDIA E IGUAL XXX
SITUACAO E IGUAL A APROVADO/REPROVADO
'''